export const abi = {
  address: "0xd973c05d71a164eff27ece0abfb81e2174355ebcc5773d188a858020808639ab",
  name: "advanced_todo_list",
  friends: [],
  exposed_functions: [
    {
      name: "complete_todo",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "u64"],
      return: [],
    },
    {
      name: "create_todo",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "0x1::string::String"],
      return: [],
    },
    {
      name: "create_todo_list",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "get_todo",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "u64", "u64"],
      return: ["0x1::string::String", "bool"],
    },
    {
      name: "get_todo_list",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["address", "u64"],
    },
    {
      name: "get_todo_list_by_todo_list_obj_addr",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["address", "u64"],
    },
    {
      name: "get_todo_list_counter",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["u64"],
    },
    {
      name: "get_todo_list_obj_addr",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["address"],
    },
    {
      name: "has_todo_list",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address", "u64"],
      return: ["bool"],
    },
  ],
  structs: [
    {
      name: "Todo",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "content",
          type: "0x1::string::String",
        },
        {
          name: "completed",
          type: "bool",
        },
      ],
    },
    {
      name: "TodoList",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "owner",
          type: "address",
        },
        {
          name: "todos",
          type: "vector<0xd973c05d71a164eff27ece0abfb81e2174355ebcc5773d188a858020808639ab::advanced_todo_list::Todo>",
        },
      ],
    },
    {
      name: "UserTodoListCounter",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "counter",
          type: "u64",
        },
      ],
    },
  ],
} as const;
